apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      securityContext:
        runAsUser: 0
      hostNetwork: true
      containers:
      - name: nginx
        image: elhays/n2n-all-in-one
        command: [ "tail", "-f", "/dev/null" ]
        ports:
        - containerPort: 1024
          hostPort: 1024