apiVersion: apps/v1
kind: Deployment
metadata:
  name: n2n-server
  labels:
    app: n2n-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n2n-server
  template:
    metadata:
      labels:
        app: n2n-server
    spec:
      securityContext:
        runAsUser: 0
      hostNetwork: true
      containers:
      - name: n2n-server
        image: elhays/n2n-all-in-one
        command: [ "tail", "-f", "/dev/null" ]
        ports:
        - containerPort: 1024
          hostPort: 1024